// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ysvcwscbhufbdtvzfjbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzdmN3c2NiaHVmYmR0dnpmamJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NzkzNTQsImV4cCI6MjA3MTE1NTM1NH0.KpNXXtMba2UPcqlv1N40Oc7lGK8NdLpiFjREQoa8FVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});